services:
    backend:
        build: .
        container_name: backend
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        env_file:
            - .env
        environment:
            FLASK_DEBUG: 1
            FLASK_RUN_HOST: "0.0.0.0"
        depends_on:
            - db

    db:
        image: postgres:17
        container_name: db
        volumes:
            - postgres-data:/var/lib/postgresql/data
        env_file:
            - .env

volumes:
    postgres-data:
